// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCG4NyEMdIK5cp8zRPE3fRv9h4qYljjy1E',
    appId: '1:584697060156:web:71d106b5ab31d5d34d5c39',
    messagingSenderId: '584697060156',
    projectId: 'ngo-smvm',
    authDomain: 'ngo-smvm.firebaseapp.com',
    storageBucket: 'ngo-smvm.appspot.com',
    measurementId: 'G-1BD4MDR9FD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBikrItnYgVJW113iFZs-yERqgxM_DPUI',
    appId: '1:584697060156:android:437268bb1437846f4d5c39',
    messagingSenderId: '584697060156',
    projectId: 'ngo-smvm',
    storageBucket: 'ngo-smvm.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMFvQsf2dioxk_C_KOeAPHGXbtGmw16rM',
    appId: '1:584697060156:ios:21defd55a74440494d5c39',
    messagingSenderId: '584697060156',
    projectId: 'ngo-smvm',
    storageBucket: 'ngo-smvm.appspot.com',
    iosBundleId: 'com.example.smvm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAMFvQsf2dioxk_C_KOeAPHGXbtGmw16rM',
    appId: '1:584697060156:ios:aa00effeff9e5ac14d5c39',
    messagingSenderId: '584697060156',
    projectId: 'ngo-smvm',
    storageBucket: 'ngo-smvm.appspot.com',
    iosBundleId: 'com.example.smvm.RunnerTests',
  );
}
